### ISSUE TITLE
Remaing input after project selection

### ISSUE THREAD

**Issue by chocoelho** [carloshfoliveira/project-switcher#2] opened 2015-03-13 06:44 UTC
There's something weird happening. When you select the desired project, there's still a small window with an input part and no options, you have to toggle the switcher again in order to close it.

**Comment by stjohnjohnson** [comment] 2015-03-15 15:54
:+1: I have the same problem.

**Comment by chocoelho** [comment] 2015-03-17 12:55
Done now!

**Comment by chocoelho** [comment] 2015-03-17 13:01
I've just publish a new patch, I suggest you to update :]

**Comment by stjohnjohnson** [comment] 2015-03-18 16:34
Yeah, it's worse now.  Won't go away, even with the toggle feature.

**Comment by chocoelho** [comment] 2015-03-18 17:14
Would please describe what happened? A screenshot might help understand what's going on.

**Comment by stjohnjohnson** [comment] 2015-03-18 18:18
![sample-bug](https://cloud.githubusercontent.com/assets/622065/6716138/8475ec96-cd60-11e4-81d6-e092e658d2a4.gif)

**Comment by stjohnjohnson** [comment] 2015-03-18 18:19
takes a couple clicks/enters for it to go away.

**Comment by chocoelho** [comment] 2015-03-18 21:50
Okay, is it an OS X? I'm gonna test and patch it asap.

**Comment by chocoelho** [comment] 2015-03-19 18:32
@stjohnjohnson what Atom version are you using? I've just tested with OS X Yosemite + latest Atom version and it was OK.

**Comment by stjohnjohnson** [comment] 2015-03-20 03:05
I just restarted and reloaded a bunch of times.  I couldn't reproduce it anymore.  Hmm.

I chalk it up to Atom's craziness.  You can close this.

**Closed as completed** 2015-03-20 10:03 UTC
